### ISSUE TITLE
Full documentation of Owner available on project website?

### ISSUE THREAD

**Issue by thungsten** [matteobaccan/matteobaccan#10]
Hi,

Unfortunately I seem to be unable to access the OWNERS documentation on [http://owner.aeonbits.org/docs/welcome](http://owner.aeonbits.org/docs/welcome).
Is this an error, is there a maintenance going on or is there a move to another page going on?
Will you output it into a website with online documentation again?

Best regards,

Thorsten

**Comment by matteobaccan** [comment]
Hi

it's true: I'll check the reason for this. Seem that the site aeonbits was not renewed.
If a renewal is impossible: I'll move all to a new hosting

ciao
matteo

**Comment by thungsten** [comment]
Thanks for the info Matteo!

Is there by any chance any other source for the documentation I could use meanwhile, e.g. via github?

Or, maybe you/anybody else developing Owner can answer the following question, while the documentation is not available:

I have to parse an config with a prefix for the keys (I think this is easily doable), sth. like "de.servers".
But beneath the prefix there is a unknown number of "dynamic" keys (de.servers.fra, de.servers.muc, de.servers.txl, ...) , and under each of these a common sub-structure is defined, so imagine sth. like 

```
de.servers.fra
de.servers.fra.host=bas
de.servers.fra.idp=bar
de.servers.fra.email=foo@bar.bat
de.servers.muc
de.servers.muc.host=bat
de.servers.muc.idp=baz
de.servers.muc.email=foo@bar.baz
de.servers.txl
de.servers.txl.host=bat
de.servers.txl.idp=bar
de.servers.txl.email=foo@bat.baz
```

The issue I have is, I don't know the values of the "sub-tree parent" keys (fra, muc, txl, ...), therefore I can't add the right property value(s).
AFAIR there is an example, how to solve such things, but I don't remember.
I guess once I solved this, it is not a real issue to read the repeating elements within the "sub-tree roots" (even if the sub-tree roots are not there) , e.g.
```
de.servers.fra.host=...
de.servers.fra.idp=...
de.servers.fra.email=...
de.servers.muc.host=...
de.servers.muc.idp=...
de.servers.muc.email=...
de.servers.txl.host=...
de.servers.txl.idp=...
de.servers.txl.email=...
```

Best regards

Thorsten

**Comment by matteobaccan** [comment]
Hi

I have moved all documentation here

https://matteobaccan.github.io/owner/

Now is all on github and github pages

ciao
matteo
