### ISSUE TITLE
Consegna per segreteria

### ISSUE THREAD

**Issue by VittorioMeloni** [matteobaccan/matteobaccan#15]
Buongiorno professore, scusi il disturbo.
Per la segreteria va bene se le porto una versione cartacea della presentazione?
Per gli altri corsi di solito stampiamo più slide per pagina in bianco e nero giusto per consegnare qualcosa.
Ovviamente all'esame presenterò al pc a colori.
Per evitare chiavette o CD.

**Comment by matteobaccan** [comment]
Va bene la carta, ma porta uno ZIP che la chiavetta la metto io
