### ISSUE TITLE
problema burger menu

### ISSUE THREAD

**Issue by GiuliaVessoso** [matteobaccan/matteobaccan#17]
buongiorno, scusi il disturbo..avrei un problema con il mio sito, quando vado in modalità mobile, il mio burger menù non va, e non capisco il perchè e inoltre quando lo apro su google chrome, ovunque clicco compare il cursore lampeggiante come se fosse una casella di testo, lo fa ovunque. Mi faccia sapere, grazie mille

**Comment by matteobaccan** [comment]
Ciao

inizia a sistemare la pagina

https://validator.w3.org/nu/?doc=https%3A%2F%2Fzephyr-agenziaviaggi.netlify.app%2F

riporta che hai iniziato la pagina con

html:

quei 5 caratteri sono da eliminare
Inizia col fare quello e poi verifica l'altezza della barra che appare sul burger menu: mi sembra troppo alta.

Al momento non ho notato cursori lampeggianti
