### ISSUE TITLE
Progetto esame

### ISSUE THREAD

**Issue by NoemiZanforlin** [matteobaccan/matteobaccan#18]
Buongiorno professore, volevo chiederle se poteva controllare il mio sito, devo solo più capire come mai non mi funziona più il burger menù in modalità mobile, solo perché ieri  ho controllato e funzionava bene. 

La ringrazio già in anticipo.

**Comment by matteobaccan** [comment]
Ciao

è come se scripts.js fosse tronco.
Se guardi l'ultimo aggiornamento

https://github.com/NoemiZanforlin/sito-esame/commit/21fc357725d720ab4bcc36732ee4e73b5c2f298c

hai levato queste righe in testa: che attivano lo script al document ready e abilitano il burger

$(document).ready(function() {
    // Inizializzazione del menu mobile
    $('.toast-menu-button').on('click', function() {
        $('.toast-menu').toggleClass('active');
    });
