### ISSUE TITLE
problematiche progetto esame

### ISSUE THREAD

**Issue by GiuliaVessoso** [matteobaccan/matteobaccan#19]
salve, volevo dirle che sono riuscita a risolvere il problema, ma ora non mi funziona più lo slide nella versione mobile..inoltre quando clicco il menù, ad esempio "come funziona". mi riporta alla sezione corretta ma un pò più sotto rispetto all'inizio, sia nella versione mobile che web..nel burger menu invece, quando lo clicco, mi copre sia il logo che la sezione esperienze.. forse è per questo che lo slider non va più, mi faccia sapere grazie

**Comment by matteobaccan** [comment]
ciao

ho visto lo slider funzionante: hai corretto la cosa?

**Comment by GiuliaVessoso** [comment]
Buongiorno! Si sono riuscita a risolvere lo slider




Il giorno lun 9 set 2024 alle 01:23 Matteo Baccan ***@***.***>
ha scritto:
